/*
 * Decompiled with CFR 0_119.
 */
package com.bekvon.bukkit.residence.containers;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;

public enum lm {
    Invalid_Player((Object)"&cInvalid player name...", new String[0]),
    Invalid_World((Object)"&cInvalid world...", new String[0]),
    Invalid_Residence((Object)"&cInvalid Residence...", new String[0]),
    Invalid_Subzone((Object)"&cInvalid Subzone...", new String[0]),
    Invalid_Direction((Object)"&cInvalid Direction...", new String[0]),
    Invalid_Amount((Object)"&cInvalid Amount...", new String[0]),
    Invalid_Cost((Object)"&cInvalid Cost...", new String[0]),
    Invalid_Days((Object)"&cInvalid number of days...", new String[0]),
    Invalid_Material((Object)"&cInvalid Material...", new String[0]),
    Invalid_Boolean((Object)"&cInvalid value, must be &6true(t) &cor &6false(f)", new String[0]),
    Invalid_Area((Object)"&cInvalid Area...", new String[0]),
    Invalid_Group((Object)"&cInvalid Group...", new String[0]),
    Invalid_MessageType((Object)"&cMessage type must be enter or remove.", new String[0]),
    Invalid_Flag((Object)"&cInvalid Flag...", new String[0]),
    Invalid_FlagState((Object)"&cInvalid flag state, must be &6true(t)&c, &6false(f)&c, or &6remove(r)", new String[0]),
    Invalid_List((Object)"&eUnknown list type, must be &6blacklist &eor &6ignorelist.", new String[0]),
    Invalid_Page((Object)"&eInvalid Page...", new String[0]),
    Invalid_Help((Object)"&cInvalid Help Page...", new String[0]),
    Invalid_NameCharacters((Object)"&cName contained unallowed characters...", new String[0]),
    Area_Exists((Object)"&cArea name already exists.", new String[0]),
    Area_Create((Object)"&eResidence Area created, ID &6%1", new String[0]),
    Area_DiffWorld((Object)"&cArea is in a different world from residence.", new String[0]),
    Area_Collision((Object)"&cArea collides with residence &6%1", new String[0]),
    Area_SubzoneCollision((Object)"&cArea collides with subzone &6%1", new String[0]),
    Area_NonExist((Object)"&cNo such area exists.", new String[0]),
    Area_InvalidName((Object)"&cInvalid Area Name...", new String[0]),
    Area_ToSmallX((Object)"&cYour &6X &cselection length (&6%1&c) is too small. &eAllowed &6%2 &eand more.", new String[0]),
    Area_ToSmallY((Object)"&cYour selection height (&6%1&c) is too small. &eAllowed &6%2 &eand more.", new String[0]),
    Area_ToSmallZ((Object)"&cYour &6Z &cselection length (&6%1&c) is too small. &eAllowed &6%2 &eand more.", new String[0]),
    Area_ToBigX((Object)"&cYour &6X &cselection length (&6%1&c) is too big. &eAllowed &6%2 &eand less.", new String[0]),
    Area_ToBigY((Object)"&cYour selection height (&6%1&c) is too big. &eAllowed &6%2 &eand less.", new String[0]),
    Area_ToBigZ((Object)"&cYour &6Z &cselection length (&6%1&c) is too big. &eAllowed &6%2 &eand less.", new String[0]),
    Area_Rename((Object)"&eRenamed area &6%1 &eto &6%2", new String[0]),
    Area_Remove((Object)"&eRemoved area &6%1...", new String[0]),
    Area_Name((Object)"&eName: &2%1", new String[0]),
    Area_RemoveLast((Object)"&cCannot remove the last area in a residence.", new String[0]),
    Area_NotWithinParent((Object)"&cArea is not within parent area.", new String[0]),
    Area_Update((Object)"&eArea Updated...", new String[0]),
    Area_MaxPhysical((Object)"&eYou've reached the max physical areas allowed for your residence.", new String[0]),
    Area_SizeLimit((Object)"&eArea size is not within your allowed limits.", new String[0]),
    Area_HighLimit((Object)"&cYou cannot protect this high up, your limit is &6%1", new String[0]),
    Area_LowLimit((Object)"&cYou cannot protect this deep, your limit is &6%1", new String[0]),
    Select_Points((Object)"&eSelect two points first before using this command!", new String[0]),
    Select_Overlap((Object)"&cSelected points overlap with &6%1 &cregion!", new String[0]),
    Select_WorldGuardOverlap((Object)"&cSelected points overlap with &6%1 &cWorldGuard region!", new String[0]),
    Select_Success((Object)"&eSelection Successful!", new String[0]),
    Select_Fail((Object)"&cInvalid select command...", new String[0]),
    Select_Bedrock((Object)"&eSelection expanded to your lowest allowed limit.", new String[0]),
    Select_Sky((Object)"&eSelection expanded to your highest allowed limit.", new String[0]),
    Select_Area((Object)"&eSelected area &6%1 &eof residence &6%2", new String[0]),
    Select_Tool((Object)"&e- Selection Tool: &6%1", new String[0]),
    Select_PrimaryPoint((Object)"&ePlaced &6Primary &eSelection Point %1", new String[0]),
    Select_SecondaryPoint((Object)"&ePlaced &6Secondary &eSelection Point %1", new String[0]),
    Select_Primary((Object)"&ePrimary selection: &6%1", new String[0]),
    Select_Secondary((Object)"&eSecondary selection: &6%1", new String[0]),
    Select_TooHigh((Object)"&cWarning, selection went above top of map, limiting.", new String[0]),
    Select_TooLow((Object)"&cWarning, selection went below bottom of map, limiting.", new String[0]),
    Select_TotalSize((Object)"&eSelection total size: &6%1", new String[0]),
    Select_AutoEnabled((Object)"&eAuto selection mode turned &6ON&e. To disable it write &6/res select auto", new String[0]),
    Select_AutoDisabled((Object)"&eAuto selection mode turned &6OFF&e. To enable it again write &6/res select auto", new String[0]),
    Select_Disabled((Object)"&cYou don't have access to selections commands", new String[0]),
    Sign_Updated((Object)"&6%1 &esigns updated!", new String[0]),
    Sign_TopLine((Object)"[market]", new String[0]),
    Sign_DateFormat((Object)"YY/MM/dd HH:mm", new String[0]),
    Sign_ForRentTopLine((Object)"&8For Rent", new String[0]),
    Sign_ForRentPriceLine((Object)"&8%1&f/&8%2&f/&8%3", new String[0]),
    Sign_ForRentResName((Object)"&8%1", new String[0]),
    Sign_ForRentBottomLine((Object)"&9Available", new String[0]),
    Sign_RentedAutorenewTrue((Object)"&2%1", new String[0]),
    Sign_RentedAutorenewFalse((Object)"&c%1", new String[0]),
    Sign_RentedTopLine((Object)"%1", new String[0]),
    Sign_RentedPriceLine((Object)"&8%1&f/&8%2&f/&8%3", new String[0]),
    Sign_RentedResName((Object)"&8%1", new String[0]),
    Sign_RentedBottomLine((Object)"&1%1", new String[0]),
    Sign_ForSaleTopLine((Object)"&8For Sale", new String[0]),
    Sign_ForSalePriceLine((Object)"&8%1", new String[0]),
    Sign_ForSaleResName((Object)"&8%1", new String[0]),
    Sign_ForSaleBottomLine((Object)"&5Available", new String[0]),
    Sign_LookAt((Object)"&cYou are not looking at sign", new String[0]),
    Flag_Set((Object)"&eFlag (&6%1&e) set for &6%2 &eto &6%3 &estate", new String[0]),
    Flag_SetFailed((Object)"&cYou dont have access to &6%1 &cflag", new String[0]),
    Flag_CheckTrue((Object)"&eFlag &6%1 &eapplies to player &6%2 &efor residence &6%3&e, value = &6%4", new String[0]),
    Flag_CheckFalse((Object)"&eFlag &6%1 &edoes not apply to player &6%2 &efor residence.", new String[0]),
    Flag_Cleared((Object)"&eFlags Cleared.", new String[0]),
    Flag_RemovedAll((Object)"&eAll flags removed for &6%1 &ein &6%2 &eresidence.", new String[0]),
    Flag_RemovedGroup((Object)"&eAll flags removed for &6%1 &egroup in &6%2 &eresidence.", new String[0]),
    Flag_Default((Object)"&eFlags set to default.", new String[0]),
    Flag_Deny((Object)"&cYou dont have &6%1 &cpermission<s> here.", new String[0]),
    Flag_SetDeny((Object)"&cOwner does not have access to flag &6%1", new String[0]),
    Flag_ChangeDeny((Object)"&cYou cant change &6%1 &cflag state while there is &6%2 &cplayer(s) inside.", new String[0]),
    Bank_NoAccess((Object)"&cYou dont have bank access.", new String[0]),
    Bank_Name((Object)" &eBank: &6%1", new String[0]),
    Bank_NoMoney((Object)"&cNot enough money in the bank.", new String[0]),
    Bank_Deposit((Object)"&eYou deposit &6%1 &einto the residence bank.", new String[0]),
    Bank_Withdraw((Object)"&eYou withdraw &6%1 from the residence bank.", new String[0]),
    Subzone_Rename((Object)"&eRenamed subzone &6%1 &eto &6%2", new String[0]),
    Subzone_Remove((Object)"&eSubzone &6%1 &eremoved.", new String[0]),
    Subzone_Create((Object)"&eCreated Subzone &6%1", new String[0]),
    Subzone_CreateFail((Object)"&cUnable to create subzone &6%1", new String[0]),
    Subzone_Exists((Object)"&cSubzone &6%1 &calready exists.", new String[0]),
    Subzone_Collide((Object)"&cSubzone collides with subzone &6%1", new String[0]),
    Subzone_MaxDepth((Object)"&cYou have reached the maximum allowed subzone depth.", new String[0]),
    Subzone_SelectInside((Object)"&eBoth selection points must be inside the residence.", new String[0]),
    Subzone_CantCreate((Object)"&cYou dont have permission to create residence subzone.", new String[0]),
    Subzone_CantDelete((Object)"&cYou dont have permission to delete residence subzone.", new String[0]),
    Subzone_CantDeleteNotOwnerOfParent((Object)"&cYou are not owner of parent residence to delete this subzone.", new String[0]),
    Subzone_CantContract((Object)"&cYou dont have permission to contract residence subzone.", new String[0]),
    Subzone_CantExpand((Object)"&cYou dont have permission to expand residence subzone.", new String[0]),
    Subzone_DeleteConfirm((Object)"&eAre you sure you want to delete subzone &6%1&e, use &6/res confirm &eto confirm.", new String[0]),
    Subzone_OwnerChange((Object)"&eSubzone &6%1 &eowner changed to &6%2", new String[0]),
    Residence_Hidden((Object)" &e(&6Hidden&e)", new String[0]),
    Residence_Bought((Object)"&eYou bought residence &6%1", new String[0]),
    Residence_Buy((Object)"&6%1 &ehas bought residence &6%2 &efrom you.", new String[0]),
    Residence_BuyTooBig((Object)"&cThis residence has areas bigger then your allowed max.", new String[0]),
    Residence_NotForSale((Object)"&cResidence is not for sale.", new String[0]),
    Residence_ForSale((Object)"&eResidence &6%1 &eis now for sale for &6%2", new String[0]),
    Residence_StopSelling((Object)"&cResidence is no longer for sale.", new String[0]),
    Residence_TooMany((Object)"&cYou already own the max number of residences your allowed to.", new String[0]),
    Residence_MaxRent((Object)"&cYou already are renting the maximum number of residences your allowed to.", new String[0]),
    Residence_AlreadyRent((Object)"&cResidence is already for rent...", new String[0]),
    Residence_NotForRent((Object)"&cResidence not for rent...", new String[0]),
    Residence_NotForRentOrSell((Object)"&cResidence not for rent or sell...", new String[0]),
    Residence_NotRented((Object)"&cResidence not rented.", new String[0]),
    Residence_Unrent((Object)"&eResidence &6%1 &ehas been unrented.", new String[0]),
    Residence_RemoveRentable((Object)"&eResidence &6%1 &eis no longer rentable.", new String[0]),
    Residence_ForRentSuccess((Object)"&eResidence &6%1 &eis now for rent for &6%2 &eevery &6%3 &edays.", new String[0]),
    Residence_RentSuccess((Object)"&eYou have rented Residence &6%1 &efor &6%2 &edays.", new String[0]),
    Residence_EndingRent((Object)"&eRent time is ending for &6%1 &eon &6%2", new String[0]),
    Residence_AlreadyRented((Object)"&eResidence &6%1 &ehas currently been rented to &6%2", new String[0]),
    Residence_CantAutoPay((Object)"&eResidence is not allowing auto pay, it will be set to &6false", new String[0]),
    Residence_AlreadyExists((Object)"&cA residence named &6%1 &calready exists.", new String[0]),
    Residence_Create((Object)"&eYou have created residence &6%1&e!", new String[0]),
    Residence_Rename((Object)"&eRenamed Residence &6%1 &eto &6%2", new String[0]),
    Residence_Remove((Object)"&eResidence &6%1 &ehas been removed...", new String[0]),
    Residence_CantRemove((Object)"&cResidence &6%1 &ccant be removed as &6%2 &csubzone is still rented by &6%3", new String[0]),
    Residence_MoveDeny((Object)"&cYou dont have movement permission for Residence &6%1", new String[0]),
    Residence_TeleportNoFlag((Object)"&cYou dont have teleport access for that residence.", new String[0]),
    Residence_FlagDeny((Object)"&cYou dont have &6%1 &cpermission for Residence &6%2", new String[0]),
    Residence_GiveLimits((Object)"&cCannot give residence to target player, because it is outside the target players limits.", new String[0]),
    Residence_Give((Object)"&eYou give residence &6%1 &eto player &6%2", new String[0]),
    Residence_Recieve((Object)"&eYou have recieved residence &6%1 &efrom player &6%2", new String[0]),
    Residence_ResList((Object)" &a%1. &e%2 &e- &6%3 %4&6%5", new String[0]),
    Residence_List((Object)" &e%2 &e- &6%3", new String[0]),
    Residence_TeleportNear((Object)"&eTeleported to near residence.", new String[0]),
    Residence_SetTeleportLocation((Object)"&eTeleport Location Set...", new String[0]),
    Residence_PermissionsApply((Object)"&ePermissions applied to residence.", new String[0]),
    Residence_NotOwner((Object)"&cYou are not owner of this residence", new String[0]),
    Residence_RemovePlayersResidences((Object)"&eRemoved all residences belonging to player &6%1", new String[0]),
    Residence_NotIn((Object)"&cYou are not in a Residence.", new String[0]),
    Residence_PlayerNotIn((Object)"&cPlayer standing not in your Residence area.", new String[0]),
    Residence_Kicked((Object)"&eYou were kicked from residence", new String[0]),
    Residence_In((Object)"&eYou are standing in Residence &6%1", new String[0]),
    Residence_OwnerChange((Object)"&eResidence &6%1 &eowner changed to &6%2", new String[0]),
    Residence_NonAdmin((Object)"&cYou are not a Residence admin.", new String[0]),
    Residence_Line((Object)"&eResidence: &6%1 ", new String[0]),
    Residence_RentedBy((Object)"&eRented by: &6%1", new String[0]),
    Residence_MessageChange((Object)"&eMessage Set...", new String[0]),
    Residence_CantDeleteResidence((Object)"&cYou dont have permission to delete residence.", new String[0]),
    Residence_CantExpandResidence((Object)"&cYou dont have permission to expand residence.", new String[0]),
    Residence_CantContractResidence((Object)"&cYou dont have permission to contract residence.", new String[0]),
    Residence_NoResHere((Object)"&cThere is no residence in there.", new String[0]),
    Residence_OwnerNoPermission((Object)"&cThe owner does not have permission for this.", new String[0]),
    Residence_ParentNoPermission((Object)"&cYou don't have permission to make changes to the parent zone.", new String[0]),
    Residence_ChatDisabled((Object)"&eResidence Chat Disabled...", new String[0]),
    Residence_DeleteConfirm((Object)"&eAre you sure you want to delete residence &6%1&e, use &6/res confirm &eto confirm.", new String[0]),
    Residence_ChangedMain((Object)"&eChanged main residence to &6%1", new String[0]),
    Residence_LwcRemoved((Object)"&eRemoved &6%1 &eLwc protections in &6%2ms", new String[0]),
    Residence_CanBeRented((Object)"&6%1&e can be rented for &6%2 &eper &6%3 &edays. &6/res market rent", new String[0]),
    Residence_CanBeBought((Object)"&6%1&e can be bought for &6%2&e. &6/res market buy", new String[0]),
    Residence_IsForRent((Object)"&6(For rent)", new String[0]),
    Residence_IsForSale((Object)"&6(For sale)", new String[0]),
    Residence_IsRented((Object)"&6(Rented)", new String[0]),
    Rent_Disabled((Object)"&cRent is disabled...", new String[0]),
    Rent_DisableRenew((Object)"&eResidence &6%1 &ewill now no longer re-rent upon expire.", new String[0]),
    Rent_EnableRenew((Object)"&eResidence &6%1 &ewill now automatically re-rent upon expire.", new String[0]),
    Rent_NotByYou((Object)"&cResidence is rented not by you.", new String[0]),
    Rent_isForRent((Object)"&2Residence available for renting.", new String[0]),
    Rent_MaxRentDays((Object)"&cYou cant rent for more than &6%1 &cdays at once.", new String[0]),
    Rent_OneTime((Object)"&cCan't extend rent time for this residence.", new String[0]),
    Rent_Extended((Object)"&eRent extended for aditional &6%1 &edays for &6%2 &eresidence", new String[0]),
    Rent_Expire((Object)"&eRent Expire Time: &6%1", new String[0]),
    Rent_AutoPayTurnedOn((Object)"&eAutoPay is turned &2ON", new String[0]),
    Rent_AutoPayTurnedOff((Object)"&eAutoPay is turned &cOFF", new String[0]),
    Rent_ModifyDeny((Object)"&cCannot modify a rented residence.", new String[0]),
    Rent_Days((Object)"&eRent days: &6%1", new String[0]),
    Rent_Rented((Object)" &6(Rented)", new String[0]),
    Rent_RentList((Object)" &6%1&e. &6%2 &e(&6%3&e/&6%4&e/&6%5&e) - &6%6 &6%7", new String[0]),
    Rent_EvictConfirm((Object)"&eWrite &6/res market confirm &eto evict renter from &6%1 &eresidence", new String[0]),
    Rent_UnrentConfirm((Object)"&eWrite &6/res market confirm &eto unrent &6%1 &eresidence", new String[0]),
    Rent_ReleaseConfirm((Object)"&eWrite &6/res market confirm &eto remove &6%1 &eresidence from market", new String[0]),
    command_addedAllow((Object)"&eAdded new allowed command for &6%1 &eresidence", new String[0]),
    command_removedAllow((Object)"&eRemoved allowed command for &6%1 &eresidence", new String[0]),
    command_addedBlock((Object)"&eAdded new blocked command for &6%1 &eresidence", new String[0]),
    command_removedBlock((Object)"&eRemoved blocked command for &6%1 &eresidence", new String[0]),
    command_Blocked((Object)"&eBlocked commands: &6%1", new String[0]),
    command_Allowed((Object)"&eAllowed commands: &6%1", new String[0]),
    Rentable_Land((Object)"&eRentable Land: &6", new String[0]),
    Rentable_AllowRenewing((Object)"&eCan Renew: &6%1", new String[0]),
    Rentable_StayInMarket((Object)"&eRentable stay in market: &6%1", new String[0]),
    Rentable_AllowAutoPay((Object)"&eRentable allows auto pay: &6%1", new String[0]),
    Rentable_DisableRenew((Object)"&6%1 &ewill no longer renew rentable status upon expire.", new String[0]),
    Rentable_EnableRenew((Object)"&6%1 &ewill now automatically renew rentable status upon expire.", new String[0]),
    Economy_LandForSale((Object)"&eLand For Sale:", new String[0]),
    Economy_NotEnoughMoney((Object)"&cYou dont have enough money.", new String[0]),
    Economy_MoneyCharged((Object)"&eCharged &6%1 &eto your &6%2 &eaccount.", new String[0]),
    Economy_MoneyAdded((Object)"&eGot &6%1 &eto your &6%2 &eaccount.", new String[0]),
    Economy_MoneyCredit((Object)"&eCredited &6%1 &eto your &6%2 &eaccount.", new String[0]),
    Economy_RentReleaseInvalid((Object)"&eResidence &6%1 &eis not rented or for rent.", new String[0]),
    Economy_RentSellFail((Object)"&cCannot sell a Residence if it is for rent.", new String[0]),
    Economy_SubzoneRentSellFail((Object)"&cCannot sell a Residence if its subzone set for rent.", new String[0]),
    Economy_ParentRentSellFail((Object)"&cCannot sell a Residence if its parent zone is for rent.", new String[0]),
    Economy_SubzoneSellFail((Object)"&cCannot sell a subzone.", new String[0]),
    Economy_SellRentFail((Object)"&cCannot rent a Residence if it is for sale.", new String[0]),
    Economy_ParentSellRentFail((Object)"&cCannot rent a Residence if its parent zone is for sale.", new String[0]),
    Economy_OwnerBuyFail((Object)"&cCannot buy your own land!", new String[0]),
    Economy_OwnerRentFail((Object)"&cCannot rent your own land!", new String[0]),
    Economy_AlreadySellFail((Object)"&eResidence already for sale!", new String[0]),
    Economy_LeaseRenew((Object)"&eLease valid until &6%1", new String[0]),
    Economy_LeaseRenewMax((Object)"&eLease renewed to maximum allowed", new String[0]),
    Economy_LeaseNotExpire((Object)"&eNo such lease, or lease does not expire.", new String[0]),
    Economy_LeaseRenewalCost((Object)"&eRenewal cost for area &6%1 &eis &6%2", new String[0]),
    Economy_LeaseInfinite((Object)"&eLease time set to infinite...", new String[0]),
    Economy_MarketDisabled((Object)"&cEconomy Disabled!", new String[0]),
    Economy_SellAmount((Object)"&eSell Amount: &2%1", new String[0]),
    Economy_SellList((Object)" &6%1&e. &6%2 &e(&6%3&e) - &6%4", new String[0]),
    Economy_LeaseExpire((Object)"&eLease Expire Time: &2%1", new String[0]),
    Expanding_North((Object)"&eExpanding North &6%1 &eblocks", new String[0]),
    Expanding_West((Object)"&eExpanding West &6%1 &eblocks", new String[0]),
    Expanding_South((Object)"&eExpanding South &6%1 &eblocks", new String[0]),
    Expanding_East((Object)"&eExpanding East &6%1 &eblocks", new String[0]),
    Expanding_Up((Object)"&eExpanding Up &6%1 &eblocks", new String[0]),
    Expanding_Down((Object)"&eExpanding Down &6%1 &eblocks", new String[0]),
    Contracting_North((Object)"&eContracting North &6%1 &eblocks", new String[0]),
    Contracting_West((Object)"&eContracting West &6%1 &eblocks", new String[0]),
    Contracting_South((Object)"&eContracting South &6%1 &eblocks", new String[0]),
    Contracting_East((Object)"&eContracting East &6%1 &eblocks", new String[0]),
    Contracting_Up((Object)"&eContracting Up &6%1 &eblocks", new String[0]),
    Contracting_Down((Object)"&eContracting Down &6%1 &eblocks", new String[0]),
    Shifting_North((Object)"&eShifting North &6%1 &eblocks", new String[0]),
    Shifting_West((Object)"&eShifting West &6%1 &eblocks", new String[0]),
    Shifting_South((Object)"&eShifting South &6%1 &eblocks", new String[0]),
    Shifting_East((Object)"&eShifting East &6%1 &eblocks", new String[0]),
    Shifting_Up((Object)"&eShifting Up &6%1 &eblocks", new String[0]),
    Shifting_Down((Object)"&eShifting Down &6%1 &eblocks", new String[0]),
    Limits_PGroup((Object)"&7- &ePermissions Group:&3 %1", new String[0]),
    Limits_RGroup((Object)"&7- &eResidence Group:&3 %1", new String[0]),
    Limits_Admin((Object)"&7- &eResidence Admin:&3 %1", new String[0]),
    Limits_CanCreate((Object)"&7- &eCan Create Residences:&3 %1", new String[0]),
    Limits_MaxRes((Object)"&7- &eMax Residences:&3 %1", new String[0]),
    Limits_MaxEW((Object)"&7- &eMax East/West Size:&3 %1", new String[0]),
    Limits_MaxNS((Object)"&7- &eMax North/South Size:&3 %1", new String[0]),
    Limits_MaxUD((Object)"&7- &eMax Up/Down Size:&3 %1", new String[0]),
    Limits_MinMax((Object)"&7- &eMin/Max Protection Height:&3 %1 to %2", new String[0]),
    Limits_MaxSub((Object)"&7- &eMax Subzone Depth:&3 %1", new String[0]),
    Limits_MaxRents((Object)"&7- &eMax Rents:&3 %1", new String[0]),
    Limits_MaxRentDays((Object)" &eMax Rent days:&3 %1", new String[0]),
    Limits_EnterLeave((Object)"&7- &eCan Set Enter/Leave Messages:&3 %1", new String[0]),
    Limits_NumberOwn((Object)"&7- &eNumber of Residences you own:&3 %1", new String[0]),
    Limits_Cost((Object)"&7- &eResidence Cost Per Block:&3 %1", new String[0]),
    Limits_Sell((Object)"&7- &eResidence Sell Cost Per Block:&3 %1", new String[0]),
    Limits_Flag((Object)"&7- &eFlag Permissions:&3 %1", new String[0]),
    Limits_MaxDays((Object)"&7- &eMax Lease Days:&3 %1", new String[0]),
    Limits_LeaseTime((Object)"&7- &eLease Time Given on Renew:&3 %1", new String[0]),
    Limits_RenewCost((Object)"&7- &eRenew Cost Per Block:&3 %1", new String[0]),
    Gui_Set_Title((Object)"&6%1 flags", new String[0]),
    Gui_Pset_Title((Object)"&6%1 %2 flags", new String[0]),
    Gui_Actions(new ArrayList<String>(Arrays.asList("&2Left click to enable", "&cRight click to disable", "&eShift + left click to remove")), new String[0]),
    InformationPage_TopLine((Object)"&e---< &a %1 &e >---", new String[0]),
    InformationPage_Page((Object)"&e-----< &6%1 &e>-----", new String[0]),
    InformationPage_NextPage((Object)"&e-----< &6%1 &e>-----", new String[0]),
    InformationPage_NoNextPage((Object)"&e-----------------------", new String[0]),
    InformationPage_GeneralList((Object)"&2 %1 &6- &e%2", new String[0]),
    InformationPage_FlagsList((Object)"&2 %1 &6- &e%2", new String[0]),
    InformationPage_Separator((Object)"&6\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac\u25ac", new String[0]),
    Chat_ChatChannelChange((Object)"&eChanged residence chat channel to &6%1!", new String[0]),
    Chat_ChatChannelLeave((Object)"&eLeft residence chat", new String[0]),
    Chat_JoinFirst((Object)"&4Join residence chat channel first...", new String[0]),
    Chat_InvalidChannel((Object)"&4Invalid Channel...", new String[0]),
    Chat_InvalidColor((Object)"&4Incorrect color code", new String[0]),
    Chat_NotInChannel((Object)"&4Player is not in channel", new String[0]),
    Chat_Kicked((Object)"&6%1 &ewas kicked from &6%2 &echannel", new String[0]),
    Chat_InvalidPrefixLength((Object)"&4Prefix is to long. Allowed length: %1", new String[0]),
    Chat_ChangedColor((Object)"&eResidence chat channel color changed to %1", new String[0]),
    Chat_ChangedPrefix((Object)"&eResidence chat channel prefix changed to %1", new String[0]),
    Shop_ListTopLine((Object)"&6%1 &eShop list - Page &6%2 &eof &6%3 %4", new String[0]),
    Shop_List((Object)" &e%1. &6%2 &e(&6%3&e) %4", new String[0]),
    Shop_ListVoted((Object)"&e%1 (&6%2&e)", new String[0]),
    Shop_ListLiked((Object)"&eLikes: &0%1", new String[0]),
    Shop_VotesTopLine((Object)"&6%1 &e%2 residence vote list &6- &ePage &6%3 &eof &6%4 %5", new String[0]),
    Shop_VotesList((Object)" &e%1. &6%2 &e%3 &7%4", new String[0]),
    Shop_NoDesc((Object)"&6No description", new String[0]),
    Shop_Desc((Object)"&6Description:\n%1", new String[0]),
    Shop_DescChange((Object)"&6Description changed to: %1", new String[0]),
    Shop_NewBoard((Object)"&6Successfully added new shop sign board", new String[0]),
    Shop_BoardExist((Object)"&cShop board already exists in this location", new String[0]),
    Shop_DeleteBoard((Object)"&6Right click sign of board you want to delete", new String[0]),
    Shop_DeletedBoard((Object)"&6Sign board removed", new String[0]),
    Shop_IncorrectBoard((Object)"&cThis is not sign board, try performing command again and clicking correct sign", new String[0]),
    Shop_InvalidSelection((Object)"&cLeft click with selection tool top left sign and then right click bottom right", new String[0]),
    Shop_VoteChanged((Object)"&6Vote changed from &e%1 &6to &e%2 &6for &e%3 &6residence", new String[0]),
    Shop_Voted((Object)"&6You voted, and gave &e%1 &6votes to &e%2 &6residence", new String[0]),
    Shop_Liked((Object)"&6You liked &e%1 &6residence", new String[0]),
    Shop_AlreadyLiked((Object)"&6You already liked &e%1 &6residence", new String[0]),
    Shop_NoVotes((Object)"&cThere is no registered votes for this residence", new String[0]),
    Shop_CantVote((Object)"&cResidence don't have shop flag set to true", new String[0]),
    Shop_VotedRange((Object)"&6Vote range is from &e%1 &6to &e%2", new String[0]),
    Shop_SignLines_1((Object)"&e--== &8%1 &e==--", new String[0]),
    Shop_SignLines_2((Object)"&9%1", new String[0]),
    Shop_SignLines_3((Object)"&4%1", new String[0]),
    Shop_SignLines_4((Object)"&8%1&e (&8%2&e)", new String[0]),
    Shop_SignLines_Likes4((Object)"&9Likes: &8%2", new String[0]),
    RandomTeleport_TpLimit((Object)"&eYou can't teleport so fast, please wait &6%1 &esec and try again", new String[0]),
    RandomTeleport_TeleportSuccess((Object)"&eTeleported to X:&6%1&e, Y:&6%2&e, Z:&6%3 &elocation", new String[0]),
    RandomTeleport_IncorrectLocation((Object)"&6Could not find correct teleport location, please wait &e%1 &6sec and try again.", new String[0]),
    RandomTeleport_TeleportStarted((Object)"&eTeleportation started, don't move for next &6%4 &esec.", new String[0]),
    RandomTeleport_WorldList((Object)"&ePossible worlds: &6%1", new String[0]),
    General_DisabledWorld((Object)"&cResidence plugin is disabled in this world", new String[0]),
    General_UseNumbers((Object)"&cPlease use numbers...", new String[0]),
    General_CantPlaceLava((Object)"&cYou can't place lava outside residence and higher than &6%1 &cblock level", new String[]{"Replace all text with '' to disable this message"}),
    General_CantPlaceWater((Object)"&cYou can't place Water outside residence and higher than &6%1 &cblock level", new String[]{"Replace all text with '' to disable this message"}),
    General_NoPermission((Object)"&cYou dont have permission for this.", new String[0]),
    General_NoCmdPermission((Object)"&cYou dont have permission for this command.", new String[0]),
    General_DefaultUsage((Object)"&eType &6/%1 ? &efor more info", new String[0]),
    General_MaterialGet((Object)"&eThe material name for ID &6%1 &eis &6%2", new String[0]),
    General_MarketList((Object)"&e---- &6Market List &e----", new String[0]),
    General_Separator((Object)"&e----------------------------------------------------", new String[0]),
    General_AdminOnly((Object)"&cOnly admins have access to this command.", new String[0]),
    General_InfoTool((Object)"&e- Info Tool: &6%1", new String[0]),
    General_ListMaterialAdd((Object)"&6%1 &eadded to the residence &6%2", new String[0]),
    General_ListMaterialRemove((Object)"&6%1 &eremoved from the residence &6%2", new String[0]),
    General_ItemBlacklisted((Object)"&cYou are blacklisted from using this item here.", new String[0]),
    General_WorldPVPDisabled((Object)"&cWorld PVP is disabled.", new String[0]),
    General_NoPVPZone((Object)"&cNo PVP zone.", new String[0]),
    General_InvalidHelp((Object)"&cInvalid help page.", new String[0]),
    General_TeleportDeny((Object)"&cYou dont have teleport access.", new String[0]),
    General_TeleportSuccess((Object)"&eTeleported!", new String[0]),
    General_TeleportConfirm((Object)"&cThis teleport is not safe, you will fall for &6%1 &cblocks. Use &6/res tpconfirm &cto perform teleportation anyways.", new String[0]),
    General_TeleportStarted((Object)"&eTeleportation to &6%1 &estarted, don't move for next &6%2 &esec.", new String[0]),
    General_TeleportTitle((Object)"&eTeleporting!", new String[0]),
    General_TeleportTitleTime((Object)"&6%1", new String[0]),
    General_TeleportCanceled((Object)"&eTeleportation canceled!", new String[0]),
    General_NoTeleportConfirm((Object)"&eThere is no teleports waiting for confirmation!", new String[0]),
    General_HelpPageHeader((Object)"&eHelp Pages - &6%1 &e- Page <&6%2 &eof &6%3&e>", new String[0]),
    General_ListExists((Object)"&cList already exists...", new String[0]),
    General_ListRemoved((Object)"&eList removed...", new String[0]),
    General_ListCreate((Object)"&eCreated list &6%1", new String[0]),
    General_PhysicalAreas((Object)"&ePhysical Areas", new String[0]),
    General_CurrentArea((Object)"&eCurrent Area: &6%1", new String[0]),
    General_TotalResSize((Object)"&eTotal size: &6%1m\u00b3 (%2m\u00b2)", new String[0]),
    General_TotalWorth((Object)"&eTotal worth of residence: &6%1 &e(&6%2&e)", new String[0]),
    General_NotOnline((Object)"&eTarget player must be online.", new String[0]),
    General_NextPage((Object)"&eNext Page", new String[0]),
    General_NextInfoPage((Object)"&2| &eNext Page &2>>>", new String[0]),
    General_PrevInfoPage((Object)"&2<<< &ePrev Page &2|", new String[0]),
    General_GenericPages((Object)"&ePage &6%1 &eof &6%2 &e(&6%3&e)", new String[0]),
    General_WorldEditNotFound((Object)"&cWorldEdit was not detected.", new String[0]),
    General_CoordsTop((Object)"&eX:&6%1 &eY:&6%2 &eZ:&6%3", new String[0]),
    General_CoordsBottom((Object)"&eX:&6%1 &eY:&6%2 &eZ:&6%3", new String[0]),
    General_AdminToggleTurnOn((Object)"&eAutomatic resadmin toggle turned &6On", new String[0]),
    General_AdminToggleTurnOff((Object)"&eAutomatic resadmin toggle turned &6Off", new String[0]),
    General_NoSpawn((Object)"&eYou do not have &6move &epermissions at your spawn point. Relocating", new String[0]),
    General_CompassTargetReset((Object)"&eYour compass has been reset", new String[0]),
    General_CompassTargetSet((Object)"&eYour compass now points to &6%1", new String[0]),
    General_Ignorelist((Object)"&2Ignorelist:&6", new String[0]),
    General_Blacklist((Object)"&cBlacklist:&6", new String[0]),
    General_LandCost((Object)"&eLand cost: &6%1", new String[0]),
    General_True((Object)"&2True", new String[0]),
    General_False((Object)"&cFalse", new String[0]),
    General_Removed((Object)"&6Removed", new String[0]),
    General_FlagState((Object)"&eFlag state: %1", new String[0]),
    General_Land((Object)"&eLand: &6%1", new String[0]),
    General_Cost((Object)"&eCost: &6%1 &eper &6%2 &edays", new String[0]),
    General_Status((Object)"&eStatus: %1", new String[0]),
    General_Available((Object)"&2Available", new String[0]),
    General_Size((Object)" &eSize: &6%1", new String[0]),
    General_ResidenceFlags((Object)"&eResidence flags: &6%1", new String[0]),
    General_PlayersFlags((Object)"&ePlayers flags: &6%1", new String[0]),
    General_GroupFlags((Object)"&eGroup flags: &6%1", new String[0]),
    General_OthersFlags((Object)"&eOthers flags: &6%1", new String[0]),
    General_Moved((Object)"&eMoved...", new String[0]),
    General_Name((Object)"&eName: &6%1", new String[0]),
    General_Lists((Object)"&eLists: &6", new String[0]),
    General_Residences((Object)"&eResidences&6", new String[0]),
    General_CreatedOn((Object)"&eCreated on: &6%1", new String[0]),
    General_Owner((Object)"&eOwner: &6%1", new String[0]),
    General_World((Object)"&eWorld: &6%1", new String[0]),
    General_Subzones((Object)"&eSubzones", new String[0]),
    General_NewPlayerInfo((Object)"&eIf you want to create protected area for your house, please use wooden axe to select opposite sides of your home and execute command &2/res create YourResidenceName", new String[]{"The below lines represent various messages residence sends to the players.", "Note that some messages have variables such as %1 that are inserted at runtime."});
    
    private Object text;
    private String[] comments;

    private /* varargs */ lm(String text, int comments, Object object, String ... arrstring) {
        this.text = text;
        this.comments = comments;
    }

    public Object getText() {
        return this.text;
    }

    public String[] getComments() {
        return this.comments;
    }

    public String getPath() {
        String path = this.name();
        if (!this.name().contains("Language.") && !this.name().contains("CommandHelp.")) {
            path = "Language." + this.name();
        }
        return path.replace("_", ".");
    }
}

